-- works on a 16x12 rectangle

function line()
    for i=1,16 do
        turtle.dig()
        turtle.forward()
    end
end
turtle.select(1)
turtle.refuel()

turtle.turnLeft()
line()
io.write("line 1 done")
turtle.turnLeft()
turtle.forward()
turtle.forward()
turtle.turnLeft()
line()
io.write("line 2 done")
turtle.turnRight()
turtle.forward()
turtle.turnRight()
line()
io.write("line 3 done")
turtle.turnLeft()
turtle.dig()
turtle.forward()
turtle.dig()
turtle.forward()
turtle.turnLeft()
line()
io.write("line 4 done")
turtle.turnRight()
turtle.forward()
turtle.turnRight()
line()
io.write("line 5 done")
turtle.turnLeft()
turtle.dig()
turtle.forward()
turtle.dig()
turtle.forward()
turtle.turnLeft()
line()
io.write("line 6 done")
turtle.turnRight()
turtle.forward()
turtle.turnRight()
line()
io.write("line 7 done")
turtle.turnLeft()
turtle.dig()
turtle.forward()
turtle.dig()
turtle.forward()
turtle.turnLeft()
line()
io.write("line 8 done")
turtle.turnRight()
turtle.forward()
turtle.turnRight()
line()
io.write("line 9 done")
turtle.turnLeft()
turtle.dig()
turtle.forward()
turtle.dig()
turtle.forward()
turtle.turnLeft()
line()
io.write("line 10 done")
turtle.turnRight()
turtle.forward()
turtle.turnRight()
line()
io.write("line 11 done")
turtle.turnLeft()
turtle.dig()
turtle.forward()
turtle.dig()
turtle.forward()
turtle.turnLeft()
line()
io.write("line 12 done")

turtle.turnLeft()
for i=1,17 do
    turtle.dig()
    turtle.forward()
end 
turtle.select(1)
turtle.drop()
turtle.select(2)
turtle.drop()
turtle.select(3)
turtle.drop()
turtle.select(4)
turtle.drop()
turtle.select(5)
turtle.drop()
turtle.select(6)
turtle.drop()
turtle.select(7)
turtle.drop()
turtle.select(8)
turtle.drop()
turtle.select(9)
turtle.drop()